#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : vcu_trd.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed Nov 28 15:09:07 EAT 2018
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: vcu_trd.sh [-help]
# usage: vcu_trd.sh [-lib_map_path]
# usage: vcu_trd.sh [-noclean_files]
# usage: vcu_trd.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'vcu_trd.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm lib_cdc_v1_0_2 proc_sys_reset_v5_0_12 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_17 smartconnect_v1_0 axi_protocol_checker_v2_0_3 axi_vip_v1_1_3 zynq_ultra_ps_e_vip_v1_0_3 xlconcat_v2_1_1 gtwizard_ultrascale_v1_7_4 gig_ethernet_pcs_pma_v16_1_4 v_smpte_uhdsdi_rx_v1_0_0 v_sdi_rx_vid_bridge_v2_0_0 v_vid_in_axi4s_v4_0_8 generic_baseblocks_v2_1_0 fifo_generator_v13_2_2 axi_data_fifo_v2_1_16 axi_crossbar_v2_1_18 v_smpte_uhdsdi_tx_v1_0_0 v_vid_sdi_tx_bridge_v2_0_0 axi_lite_ipif_v3_0_4 v_tc_v6_1_12 v_axi4s_vid_out_v4_0_9 xlconstant_v1_1_5 axi_protocol_converter_v2_1_17)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "vcu_trd.sh - Script generated by export_simulation (Vivado v2018.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/opt/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/sim/vcu_trd.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_proc_sys_reset_vcu_0_1/sim/vcu_trd_proc_sys_reset_vcu_0_1.vhd" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_proc_sys_reset_vcu_1_1/sim/vcu_trd_proc_sys_reset_vcu_1_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/6020/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_vcu_enc0_reg_slice_1/sim/vcu_trd_vcu_enc0_reg_slice_1.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_vcu_enc1_reg_slice_1/sim/vcu_trd_vcu_enc1_reg_slice_1.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_vcu_dec0_reg_slice_1/sim/vcu_trd_vcu_dec0_reg_slice_1.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_vcu_dec1_reg_slice_1/sim/vcu_trd_vcu_dec1_reg_slice_1.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_vcu_mcu_reg_slice_1/sim/vcu_trd_vcu_mcu_reg_slice_1.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_vcu_clk_wiz0_1/vcu_trd_vcu_clk_wiz0_1_clk_wiz.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_vcu_clk_wiz0_1/vcu_trd_vcu_clk_wiz0_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/sc_util_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_checker_v2_0_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/03a9/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b9a8/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_zynq_ultra_ps_e_0_1/sim/vcu_trd_zynq_ultra_ps_e_0_1_vip_wrapper.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_vcu_interrupt_1/sim/vcu_trd_vcu_interrupt_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work gtwizard_ultrascale_v1_7_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_bit_sync.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gte4_drp_arb.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gthe4_delay_powergood.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtye4_delay_powergood.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gthe3_cpll_cal.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gthe3_cal_freqcnt.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_rx.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_tx.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gthe4_cal_freqcnt.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_rx.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_tx.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtye4_cal_freqcnt.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_rx.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_tx.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtwiz_reset.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_rx.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_tx.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_rx.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_tx.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_reset_sync.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/2223/hdl/gtwizard_ultrascale_v1_7_reset_inv_sync.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_gig_ethernet_pcs_pma_0_1/ip_0/sim/gtwizard_ultrascale_v1_7_gthe4_channel.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_gig_ethernet_pcs_pma_0_1/ip_0/sim/vcu_trd_gig_ethernet_pcs_pma_0_1_gt_gthe4_channel_wrapper.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_gig_ethernet_pcs_pma_0_1/ip_0/sim/vcu_trd_gig_ethernet_pcs_pma_0_1_gt_gtwizard_gthe4.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_gig_ethernet_pcs_pma_0_1/ip_0/sim/vcu_trd_gig_ethernet_pcs_pma_0_1_gt_gtwizard_top.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_gig_ethernet_pcs_pma_0_1/ip_0/sim/vcu_trd_gig_ethernet_pcs_pma_0_1_gt.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work gig_ethernet_pcs_pma_v16_1_4 $vhdlan_opts \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/494d/hdl/gig_ethernet_pcs_pma_v16_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work gig_ethernet_pcs_pma_v16_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/494d/hdl/gig_ethernet_pcs_pma_v16_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_gig_ethernet_pcs_pma_0_1/synth/vcu_trd_gig_ethernet_pcs_pma_0_1_resets.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_gig_ethernet_pcs_pma_0_1/synth/vcu_trd_gig_ethernet_pcs_pma_0_1_clocking.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_gig_ethernet_pcs_pma_0_1/synth/vcu_trd_gig_ethernet_pcs_pma_0_1_support.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_gig_ethernet_pcs_pma_0_1/synth/sgmii_adapt/vcu_trd_gig_ethernet_pcs_pma_0_1_clk_gen.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_gig_ethernet_pcs_pma_0_1/synth/sgmii_adapt/vcu_trd_gig_ethernet_pcs_pma_0_1_johnson_cntr.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_gig_ethernet_pcs_pma_0_1/synth/vcu_trd_gig_ethernet_pcs_pma_0_1_reset_sync.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_gig_ethernet_pcs_pma_0_1/synth/transceiver/vcu_trd_gig_ethernet_pcs_pma_0_1_rx_elastic_buffer.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_gig_ethernet_pcs_pma_0_1/synth/sgmii_adapt/vcu_trd_gig_ethernet_pcs_pma_0_1_rx_rate_adapt.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_gig_ethernet_pcs_pma_0_1/synth/sgmii_adapt/vcu_trd_gig_ethernet_pcs_pma_0_1_sgmii_adapt.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_gig_ethernet_pcs_pma_0_1/synth/vcu_trd_gig_ethernet_pcs_pma_0_1_sync_block.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_gig_ethernet_pcs_pma_0_1/synth/transceiver/vcu_trd_gig_ethernet_pcs_pma_0_1_transceiver.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_gig_ethernet_pcs_pma_0_1/synth/sgmii_adapt/vcu_trd_gig_ethernet_pcs_pma_0_1_tx_rate_adapt.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_gig_ethernet_pcs_pma_0_1/synth/vcu_trd_gig_ethernet_pcs_pma_0_1_block.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_gig_ethernet_pcs_pma_0_1/synth/vcu_trd_gig_ethernet_pcs_pma_0_1.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_clk_wiz_1/vcu_trd_clk_wiz_1_clk_wiz.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_clk_wiz_1/vcu_trd_clk_wiz_1.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_clk_wiz_1_1/vcu_trd_clk_wiz_1_1_clk_wiz.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_clk_wiz_1_1/vcu_trd_clk_wiz_1_1.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_clk_wiz_2_1/vcu_trd_clk_wiz_2_1_clk_wiz.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_clk_wiz_2_1/vcu_trd_clk_wiz_2_1.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_clk_wiz_3_1/vcu_trd_clk_wiz_3_1_clk_wiz.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_clk_wiz_3_1/vcu_trd_clk_wiz_3_1.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_clk_wiz_4_1/vcu_trd_clk_wiz_4_1_clk_wiz.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_clk_wiz_4_1/vcu_trd_clk_wiz_4_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_smpte_uhdsdi_rx_v1_0_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_edh_fly_horz.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_decoder.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_framer.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_edh_errcnt.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_st352_pid_capture.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_edh_crc.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_edh_autodetect.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_demux_4.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_edh_flags.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_trs_restore.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_edh_video_decode.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_edh_processor.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_edh_rx.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_edh_tx.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_autorate.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_edh_loc.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_edh_fly_fsm.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_edh_fly_field.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_edh_crc16.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_transport_detect.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_edh_anc_rx.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_edh_flywheel.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_edh_fly_vert.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_to_demux.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_crc.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_crc2.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_edh_trs_detect.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_s00_axi.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work v_smpte_uhdsdi_rx_v1_0_0 $vhdlan_opts \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/cross_clk_reg.vhd" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/cross_clk_bus.vhd" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/map_pulse.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_smpte_uhdsdi_rx_v1_0_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_rx.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/bbc9/hdl/v_smpte_uhdsdi_rx_v1_0_top.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_rx_ss_0_0/bd_0/ip/ip_0/sim/bd_22f3_v_smpte_uhdsdi_rx_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_sdi_rx_vid_bridge_v2_0_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/c648/hdl/verilog/v_sdi_rx_vid_bridge_v2_0_lib.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/c648/hdl/verilog/v_sdi_rx_vid_bridge_v2_0_12g_ce_gen.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/c648/hdl/verilog/v_sdi_rx_vid_bridge_v2_0_12g_converter.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/c648/hdl/verilog/v_sdi_rx_vid_bridge_v2_0_12g_fifo.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/c648/hdl/verilog/v_sdi_rx_vid_bridge_v2_0_12g_formatter.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/c648/hdl/verilog/v_sdi_rx_vid_bridge_v2_0_12g_trs_decode.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/c648/hdl/verilog/v_sdi_rx_vid_bridge_v2_0_12g.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/c648/hdl/verilog/v_sdi_rx_vid_bridge_v2_0_3g_ce_gen.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/c648/hdl/verilog/v_sdi_rx_vid_bridge_v2_0_3g_converter.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/c648/hdl/verilog/v_sdi_rx_vid_bridge_v2_0_3g_fifo.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/c648/hdl/verilog/v_sdi_rx_vid_bridge_v2_0_3g_formatter.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/c648/hdl/verilog/v_sdi_rx_vid_bridge_v2_0_3g_sync_extract.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/c648/hdl/verilog/v_sdi_rx_vid_bridge_v2_0_3g_trs_decode.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/c648/hdl/verilog/v_sdi_rx_vid_bridge_v2_0_3g.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/c648/hdl/verilog/v_sdi_rx_vid_bridge_v2_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_rx_ss_0_0/bd_0/ip/ip_1/sim/bd_22f3_v_sdi_rx_vid_bridge_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_vid_in_axi4s_v4_0_8 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/d987/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_rx_ss_0_0/bd_0/ip/ip_2/sim/bd_22f3_v_vid_in_axi4s_0.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_rx_ss_0_0/bd_0/sim/bd_22f3.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_rx_ss_0_0/sim/vcu_trd_v_smpte_uhdsdi_rx_ss_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/7aff/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_2 $vhdlan_opts \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/247d/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/15a3/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0/bd_0/ip/ip_0/sim/bd_82d8_axi_crossbar_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_smpte_uhdsdi_tx_v1_0_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_edh_anc_rx.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_edh_flags.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_edh_loc.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_edh_processor.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_mux.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_bitrep_20b.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_edh_video_decode.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_edh_autodetect.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_edh_tx.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_edh_rx.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_channel.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_output.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_syncbit_insert.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_trsgen.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_crc2.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_insert_crc.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_scrambler.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_edh_crc16.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_st352_pid_insert.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_edh_trs_detect.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_edh_fly_horz.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_insert_ln.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_edh_fly_fsm.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_s00_axi.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_edh_errcnt.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_edh_crc.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_edh_flywheel.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_encoder.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_edh_fly_vert.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_edh_fly_field.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work v_smpte_uhdsdi_tx_v1_0_0 $vhdlan_opts \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/cross_clk_reg.vhd" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/cross_clk_bus.vhd" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/map_pulse.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_smpte_uhdsdi_tx_v1_0_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_tx.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/8b05/hdl/v_smpte_uhdsdi_tx_v1_0_top.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0/bd_0/ip/ip_1/sim/bd_82d8_v_smpte_uhdsdi_tx_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_vid_sdi_tx_bridge_v2_0_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/108c/hdl/verilog/v_vid_sdi_tx_bridge_v2_0_lib.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/108c/hdl/verilog/v_vid_sdi_tx_bridge_v2_0_12g_ce_gen.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/108c/hdl/verilog/v_vid_sdi_tx_bridge_v2_0_12g_clamp.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/108c/hdl/verilog/v_vid_sdi_tx_bridge_v2_0_12g_converter.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/108c/hdl/verilog/v_vid_sdi_tx_bridge_v2_0_12g_embedder.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/108c/hdl/verilog/v_vid_sdi_tx_bridge_v2_0_12g_fifo.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/108c/hdl/verilog/v_vid_sdi_tx_bridge_v2_0_12g_formatter.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/108c/hdl/verilog/v_vid_sdi_tx_bridge_v2_0_12g.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/108c/hdl/verilog/v_vid_sdi_tx_bridge_v2_0_3g_ce_gen.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/108c/hdl/verilog/v_vid_sdi_tx_bridge_v2_0_3g_converter.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/108c/hdl/verilog/v_vid_sdi_tx_bridge_v2_0_3g_embedder.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/108c/hdl/verilog/v_vid_sdi_tx_bridge_v2_0_3g_fifo.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/108c/hdl/verilog/v_vid_sdi_tx_bridge_v2_0_3g_formatter.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/108c/hdl/verilog/v_vid_sdi_tx_bridge_v2_0_3g.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/108c/hdl/verilog/v_vid_sdi_tx_bridge_v2_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0/bd_0/ip/ip_2/sim/bd_82d8_v_vid_sdi_tx_bridge_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_1_12 $vhdlan_opts \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/6694/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_axi4s_vid_out_v4_0_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/9a07/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0/bd_0/ip/ip_3/sim/bd_82d8_v_axi4s_vid_out_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0/bd_0/ip/ip_4/sim/bd_82d8_v_tc_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/f1c3/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0/bd_0/ip/ip_5/sim/bd_82d8_const_1_0.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0/bd_0/sim/bd_82d8.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0/sim/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_clk_wiz_0_1/vcu_trd_clk_wiz_0_1_clk_wiz.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_clk_wiz_0_1/vcu_trd_clk_wiz_0_1.v" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_xbar_1/sim/vcu_trd_xbar_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ccfb/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/b65a" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/5bb9/hdl/verilog" +incdir+"$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ipshared/e4d1/hdl" +incdir+"/opt/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vcu_trd.srcs/sources_1/bd/vcu_trd/ip/vcu_trd_auto_pc_6/sim/vcu_trd_auto_pc_6.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.vcu_trd xil_defaultlib.glbl -o vcu_trd_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./vcu_trd_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./vcu_trd.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/brainiarc7/designs/vcu_trd/vcu_trd.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key vcu_trd_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc vcu_trd_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./vcu_trd.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: vcu_trd.sh [-help]\n\
Usage: vcu_trd.sh [-lib_map_path]\n\
Usage: vcu_trd.sh [-reset_run]\n\
Usage: vcu_trd.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
