# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Xilinx/UltraZed-EV-CC-Master-XDC.xdc

# Block Designs: bd/vcu_trd/vcu_trd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_trd || ORIG_REF_NAME==vcu_trd} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_vcu_0_1/vcu_trd_vcu_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_trd_vcu_0_1 || ORIG_REF_NAME==vcu_trd_vcu_0_1} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_proc_sys_reset_vcu_0_1/vcu_trd_proc_sys_reset_vcu_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_trd_proc_sys_reset_vcu_0_1 || ORIG_REF_NAME==vcu_trd_proc_sys_reset_vcu_0_1} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_proc_sys_reset_vcu_1_1/vcu_trd_proc_sys_reset_vcu_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_trd_proc_sys_reset_vcu_1_1 || ORIG_REF_NAME==vcu_trd_proc_sys_reset_vcu_1_1} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_vcu_enc0_reg_slice_1/vcu_trd_vcu_enc0_reg_slice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_trd_vcu_enc0_reg_slice_1 || ORIG_REF_NAME==vcu_trd_vcu_enc0_reg_slice_1} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_vcu_enc1_reg_slice_1/vcu_trd_vcu_enc1_reg_slice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_trd_vcu_enc1_reg_slice_1 || ORIG_REF_NAME==vcu_trd_vcu_enc1_reg_slice_1} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_vcu_dec0_reg_slice_1/vcu_trd_vcu_dec0_reg_slice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_trd_vcu_dec0_reg_slice_1 || ORIG_REF_NAME==vcu_trd_vcu_dec0_reg_slice_1} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_vcu_dec1_reg_slice_1/vcu_trd_vcu_dec1_reg_slice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_trd_vcu_dec1_reg_slice_1 || ORIG_REF_NAME==vcu_trd_vcu_dec1_reg_slice_1} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_vcu_mcu_reg_slice_1/vcu_trd_vcu_mcu_reg_slice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_trd_vcu_mcu_reg_slice_1 || ORIG_REF_NAME==vcu_trd_vcu_mcu_reg_slice_1} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_vcu_axi_lite_0_1/vcu_trd_vcu_axi_lite_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_trd_vcu_axi_lite_0_1 || ORIG_REF_NAME==vcu_trd_vcu_axi_lite_0_1} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_vcu_clk_wiz0_1/vcu_trd_vcu_clk_wiz0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_trd_vcu_clk_wiz0_1 || ORIG_REF_NAME==vcu_trd_vcu_clk_wiz0_1} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_zynq_ultra_ps_e_0_1/vcu_trd_zynq_ultra_ps_e_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_trd_zynq_ultra_ps_e_0_1 || ORIG_REF_NAME==vcu_trd_zynq_ultra_ps_e_0_1} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_vcu_interrupt_1/vcu_trd_vcu_interrupt_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_trd_vcu_interrupt_1 || ORIG_REF_NAME==vcu_trd_vcu_interrupt_1} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_gig_ethernet_pcs_pma_0_1/vcu_trd_gig_ethernet_pcs_pma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_trd_gig_ethernet_pcs_pma_0_1 || ORIG_REF_NAME==vcu_trd_gig_ethernet_pcs_pma_0_1} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_gig_ethernet_pcs_pma_0_1/ip_0/vcu_trd_gig_ethernet_pcs_pma_0_1_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_trd_gig_ethernet_pcs_pma_0_1_gt || ORIG_REF_NAME==vcu_trd_gig_ethernet_pcs_pma_0_1_gt} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_clk_wiz_1/vcu_trd_clk_wiz_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_trd_clk_wiz_1 || ORIG_REF_NAME==vcu_trd_clk_wiz_1} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_clk_wiz_1_1/vcu_trd_clk_wiz_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_trd_clk_wiz_1_1 || ORIG_REF_NAME==vcu_trd_clk_wiz_1_1} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_clk_wiz_2_1/vcu_trd_clk_wiz_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_trd_clk_wiz_2_1 || ORIG_REF_NAME==vcu_trd_clk_wiz_2_1} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_clk_wiz_3_1/vcu_trd_clk_wiz_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_trd_clk_wiz_3_1 || ORIG_REF_NAME==vcu_trd_clk_wiz_3_1} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_clk_wiz_4_1/vcu_trd_clk_wiz_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_trd_clk_wiz_4_1 || ORIG_REF_NAME==vcu_trd_clk_wiz_4_1} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_rx_ss_0_0/vcu_trd_v_smpte_uhdsdi_rx_ss_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_trd_v_smpte_uhdsdi_rx_ss_0_0 || ORIG_REF_NAME==vcu_trd_v_smpte_uhdsdi_rx_ss_0_0} -quiet] -quiet

# Block Designs: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_rx_ss_0_0/bd_0/bd_22f3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_22f3 || ORIG_REF_NAME==bd_22f3} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_rx_ss_0_0/bd_0/ip/ip_0/bd_22f3_v_smpte_uhdsdi_rx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_22f3_v_smpte_uhdsdi_rx_0 || ORIG_REF_NAME==bd_22f3_v_smpte_uhdsdi_rx_0} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_rx_ss_0_0/bd_0/ip/ip_1/bd_22f3_v_sdi_rx_vid_bridge_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_22f3_v_sdi_rx_vid_bridge_0 || ORIG_REF_NAME==bd_22f3_v_sdi_rx_vid_bridge_0} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_rx_ss_0_0/bd_0/ip/ip_2/bd_22f3_v_vid_in_axi4s_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_22f3_v_vid_in_axi4s_0 || ORIG_REF_NAME==bd_22f3_v_vid_in_axi4s_0} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_trd_v_smpte_uhdsdi_tx_ss_0_0 || ORIG_REF_NAME==vcu_trd_v_smpte_uhdsdi_tx_ss_0_0} -quiet] -quiet

# Block Designs: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0/bd_0/bd_82d8.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_82d8 || ORIG_REF_NAME==bd_82d8} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0/bd_0/ip/ip_0/bd_82d8_axi_crossbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_82d8_axi_crossbar_0 || ORIG_REF_NAME==bd_82d8_axi_crossbar_0} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0/bd_0/ip/ip_1/bd_82d8_v_smpte_uhdsdi_tx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_82d8_v_smpte_uhdsdi_tx_0 || ORIG_REF_NAME==bd_82d8_v_smpte_uhdsdi_tx_0} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0/bd_0/ip/ip_2/bd_82d8_v_vid_sdi_tx_bridge_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_82d8_v_vid_sdi_tx_bridge_0 || ORIG_REF_NAME==bd_82d8_v_vid_sdi_tx_bridge_0} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0/bd_0/ip/ip_3/bd_82d8_v_axi4s_vid_out_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_82d8_v_axi4s_vid_out_0 || ORIG_REF_NAME==bd_82d8_v_axi4s_vid_out_0} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0/bd_0/ip/ip_4/bd_82d8_v_tc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_82d8_v_tc_0 || ORIG_REF_NAME==bd_82d8_v_tc_0} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0/bd_0/ip/ip_5/bd_82d8_const_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_82d8_const_1_0 || ORIG_REF_NAME==bd_82d8_const_1_0} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_clk_wiz_0_1/vcu_trd_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_trd_clk_wiz_0_1 || ORIG_REF_NAME==vcu_trd_clk_wiz_0_1} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_xbar_1/vcu_trd_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_trd_xbar_1 || ORIG_REF_NAME==vcu_trd_xbar_1} -quiet] -quiet

# IP: bd/vcu_trd/ip/vcu_trd_auto_pc_0/vcu_trd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vcu_trd_auto_pc_0 || ORIG_REF_NAME==vcu_trd_auto_pc_0} -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_vcu_0_1/constraints/vcu.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_vcu_0_1 || ORIG_REF_NAME==vcu_trd_vcu_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_vcu_0_1/vcu_trd_vcu_0_1_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_proc_sys_reset_vcu_0_1/vcu_trd_proc_sys_reset_vcu_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_proc_sys_reset_vcu_0_1 || ORIG_REF_NAME==vcu_trd_proc_sys_reset_vcu_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_proc_sys_reset_vcu_0_1/vcu_trd_proc_sys_reset_vcu_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_proc_sys_reset_vcu_0_1 || ORIG_REF_NAME==vcu_trd_proc_sys_reset_vcu_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_proc_sys_reset_vcu_0_1/vcu_trd_proc_sys_reset_vcu_0_1_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_proc_sys_reset_vcu_1_1/vcu_trd_proc_sys_reset_vcu_1_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_proc_sys_reset_vcu_1_1 || ORIG_REF_NAME==vcu_trd_proc_sys_reset_vcu_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_proc_sys_reset_vcu_1_1/vcu_trd_proc_sys_reset_vcu_1_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_proc_sys_reset_vcu_1_1 || ORIG_REF_NAME==vcu_trd_proc_sys_reset_vcu_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_proc_sys_reset_vcu_1_1/vcu_trd_proc_sys_reset_vcu_1_1_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_vcu_enc0_reg_slice_1/vcu_trd_vcu_enc0_reg_slice_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_vcu_enc0_reg_slice_1 || ORIG_REF_NAME==vcu_trd_vcu_enc0_reg_slice_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_vcu_enc0_reg_slice_1/vcu_trd_vcu_enc0_reg_slice_1_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_vcu_enc1_reg_slice_1/vcu_trd_vcu_enc1_reg_slice_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_vcu_enc1_reg_slice_1 || ORIG_REF_NAME==vcu_trd_vcu_enc1_reg_slice_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_vcu_enc1_reg_slice_1/vcu_trd_vcu_enc1_reg_slice_1_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_vcu_dec0_reg_slice_1/vcu_trd_vcu_dec0_reg_slice_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_vcu_dec0_reg_slice_1 || ORIG_REF_NAME==vcu_trd_vcu_dec0_reg_slice_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_vcu_dec0_reg_slice_1/vcu_trd_vcu_dec0_reg_slice_1_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_vcu_dec1_reg_slice_1/vcu_trd_vcu_dec1_reg_slice_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_vcu_dec1_reg_slice_1 || ORIG_REF_NAME==vcu_trd_vcu_dec1_reg_slice_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_vcu_dec1_reg_slice_1/vcu_trd_vcu_dec1_reg_slice_1_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_vcu_mcu_reg_slice_1/vcu_trd_vcu_mcu_reg_slice_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_vcu_mcu_reg_slice_1 || ORIG_REF_NAME==vcu_trd_vcu_mcu_reg_slice_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_vcu_mcu_reg_slice_1/vcu_trd_vcu_mcu_reg_slice_1_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_vcu_clk_wiz0_1/vcu_trd_vcu_clk_wiz0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_vcu_clk_wiz0_1 || ORIG_REF_NAME==vcu_trd_vcu_clk_wiz0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_vcu_clk_wiz0_1/vcu_trd_vcu_clk_wiz0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_vcu_clk_wiz0_1 || ORIG_REF_NAME==vcu_trd_vcu_clk_wiz0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_vcu_clk_wiz0_1/vcu_trd_vcu_clk_wiz0_1_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_zynq_ultra_ps_e_0_1/vcu_trd_zynq_ultra_ps_e_0_1_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_zynq_ultra_ps_e_0_1/vcu_trd_zynq_ultra_ps_e_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_zynq_ultra_ps_e_0_1 || ORIG_REF_NAME==vcu_trd_zynq_ultra_ps_e_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_gig_ethernet_pcs_pma_0_1/ip_0/synth/vcu_trd_gig_ethernet_pcs_pma_0_1_gt_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_gig_ethernet_pcs_pma_0_1/ip_0/synth/vcu_trd_gig_ethernet_pcs_pma_0_1_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_gig_ethernet_pcs_pma_0_1_gt || ORIG_REF_NAME==vcu_trd_gig_ethernet_pcs_pma_0_1_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_gig_ethernet_pcs_pma_0_1/vcu_trd_gig_ethernet_pcs_pma_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_gig_ethernet_pcs_pma_0_1 || ORIG_REF_NAME==vcu_trd_gig_ethernet_pcs_pma_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_gig_ethernet_pcs_pma_0_1/synth/vcu_trd_gig_ethernet_pcs_pma_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_gig_ethernet_pcs_pma_0_1 || ORIG_REF_NAME==vcu_trd_gig_ethernet_pcs_pma_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_gig_ethernet_pcs_pma_0_1/synth/vcu_trd_gig_ethernet_pcs_pma_0_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_gig_ethernet_pcs_pma_0_1 || ORIG_REF_NAME==vcu_trd_gig_ethernet_pcs_pma_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_gig_ethernet_pcs_pma_0_1/synth/vcu_trd_gig_ethernet_pcs_pma_0_1_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_clk_wiz_1/vcu_trd_clk_wiz_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_clk_wiz_1 || ORIG_REF_NAME==vcu_trd_clk_wiz_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_clk_wiz_1/vcu_trd_clk_wiz_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_clk_wiz_1 || ORIG_REF_NAME==vcu_trd_clk_wiz_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_clk_wiz_1/vcu_trd_clk_wiz_1_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_clk_wiz_1_1/vcu_trd_clk_wiz_1_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_clk_wiz_1_1 || ORIG_REF_NAME==vcu_trd_clk_wiz_1_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_clk_wiz_1_1/vcu_trd_clk_wiz_1_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_clk_wiz_1_1 || ORIG_REF_NAME==vcu_trd_clk_wiz_1_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_clk_wiz_1_1/vcu_trd_clk_wiz_1_1_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_clk_wiz_2_1/vcu_trd_clk_wiz_2_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_clk_wiz_2_1 || ORIG_REF_NAME==vcu_trd_clk_wiz_2_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_clk_wiz_2_1/vcu_trd_clk_wiz_2_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_clk_wiz_2_1 || ORIG_REF_NAME==vcu_trd_clk_wiz_2_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_clk_wiz_2_1/vcu_trd_clk_wiz_2_1_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_clk_wiz_3_1/vcu_trd_clk_wiz_3_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_clk_wiz_3_1 || ORIG_REF_NAME==vcu_trd_clk_wiz_3_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_clk_wiz_3_1/vcu_trd_clk_wiz_3_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_clk_wiz_3_1 || ORIG_REF_NAME==vcu_trd_clk_wiz_3_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_clk_wiz_3_1/vcu_trd_clk_wiz_3_1_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_clk_wiz_4_1/vcu_trd_clk_wiz_4_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_clk_wiz_4_1 || ORIG_REF_NAME==vcu_trd_clk_wiz_4_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_clk_wiz_4_1/vcu_trd_clk_wiz_4_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_clk_wiz_4_1 || ORIG_REF_NAME==vcu_trd_clk_wiz_4_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_clk_wiz_4_1/vcu_trd_clk_wiz_4_1_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_rx_ss_0_0/bd_0/ip/ip_0/bd_22f3_v_smpte_uhdsdi_rx_0_core.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_rx_ss_0_0/bd_0/ip/ip_0/bd_22f3_v_smpte_uhdsdi_rx_0_clock.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_22f3_v_smpte_uhdsdi_rx_0 || ORIG_REF_NAME==bd_22f3_v_smpte_uhdsdi_rx_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_rx_ss_0_0/bd_0/ip/ip_0/bd_22f3_v_smpte_uhdsdi_rx_0_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_rx_ss_0_0/bd_0/ip/ip_1/bd_22f3_v_sdi_rx_vid_bridge_0_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_rx_ss_0_0/bd_0/ip/ip_2/bd_22f3_v_vid_in_axi4s_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_22f3_v_vid_in_axi4s_0 || ORIG_REF_NAME==bd_22f3_v_vid_in_axi4s_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_rx_ss_0_0/bd_0/ip/ip_2/bd_22f3_v_vid_in_axi4s_0_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_rx_ss_0_0/bd_0/bd_22f3_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_rx_ss_0_0/vcu_trd_v_smpte_uhdsdi_rx_ss_0_0_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0/bd_0/ip/ip_0/bd_82d8_axi_crossbar_0_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0/bd_0/ip/ip_1/bd_82d8_v_smpte_uhdsdi_tx_0_core.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0/bd_0/ip/ip_1/bd_82d8_v_smpte_uhdsdi_tx_0_clock.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_82d8_v_smpte_uhdsdi_tx_0 || ORIG_REF_NAME==bd_82d8_v_smpte_uhdsdi_tx_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0/bd_0/ip/ip_1/bd_82d8_v_smpte_uhdsdi_tx_0_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0/bd_0/ip/ip_2/bd_82d8_v_vid_sdi_tx_bridge_0_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0/bd_0/ip/ip_3/bd_82d8_v_axi4s_vid_out_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_82d8_v_axi4s_vid_out_0 || ORIG_REF_NAME==bd_82d8_v_axi4s_vid_out_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0/bd_0/ip/ip_3/bd_82d8_v_axi4s_vid_out_0_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0/bd_0/ip/ip_4/bd_82d8_v_tc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_82d8_v_tc_0 || ORIG_REF_NAME==bd_82d8_v_tc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0/bd_0/ip/ip_4/bd_82d8_v_tc_0_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0/bd_0/bd_82d8_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0/vcu_trd_v_smpte_uhdsdi_tx_ss_0_0_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_clk_wiz_0_1/vcu_trd_clk_wiz_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_clk_wiz_0_1 || ORIG_REF_NAME==vcu_trd_clk_wiz_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_clk_wiz_0_1/vcu_trd_clk_wiz_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vcu_trd_clk_wiz_0_1 || ORIG_REF_NAME==vcu_trd_clk_wiz_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/vcu_trd/ip/vcu_trd_clk_wiz_0_1/vcu_trd_clk_wiz_0_1_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_xbar_1/vcu_trd_xbar_1_ooc.xdc

# XDC: bd/vcu_trd/ip/vcu_trd_auto_pc_0/vcu_trd_auto_pc_0_ooc.xdc

# XDC: bd/vcu_trd/vcu_trd_ooc.xdc
